services:
  - type: web
    name: api-rutas-bogota
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OSMNX_USE_CACHE
        value: "True"
